# Generated by Django 4.0 on 2022-02-09 01:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exemplarlivro',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.user'),
        ),
        migrations.AlterField(
            model_name='genero',
            name='nome',
            field=models.CharField(help_text='Entre com um gênero de livro. Ex: Ficção científica.', max_length=200),
        ),
        migrations.AlterField(
            model_name='livro',
            name='resumo',
            field=models.TextField(help_text='Digite uma descrição do livro', max_length=1000),
        ),
    ]
